version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algoapp-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: "file:./prisma/dev.db"
      TRADINGVIEW_WEBHOOK_SECRET: tv_sec_prod_882910
      DELTA_API_KEY: ${DELTA_API_KEY:-""}
      DELTA_API_SECRET: ${DELTA_API_SECRET:-""}
    ports:
      - "4000:4000"
    volumes:
      - sqlite_data:/app/backend/prisma

volumes:
  sqlite_data:
